import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/header";
import { TodoList } from "../components/todo-list";
import { TodoProvider } from "../store/todo-provider";

const Home: NextPage = () => {
  return (
    <div className="grid place-items-center w-full min-h-screen bg-disc-dark-not-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TodoProvider>
        <TodoList />
      </TodoProvider>
    </div>
  );
};

export default Home;
